// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 72tUXrciMYQcBHG6D1vyXy
// Component: hTinKt-4uikWq
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconButton from "../../IconButton"; // plasmic-import: _4_i9nb16DyA6/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_dls_css from "../dls/plasmic_dls.module.css"; // plasmic-import: wKYGFqyVBmDVb7fPCj2tLF/projectcss
import projectcss from "./plasmic_copy_of_text_messaging_app.module.css"; // plasmic-import: 72tUXrciMYQcBHG6D1vyXy/projectcss
import sty from "./PlasmicNavLevel1.module.css"; // plasmic-import: hTinKt-4uikWq/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: _YyChvp-V52F2m/icon

export type PlasmicNavLevel1__VariantMembers = {};

export type PlasmicNavLevel1__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavLevel1__VariantsArgs;
export const PlasmicNavLevel1__VariantProps = new Array<VariantPropType>();

export type PlasmicNavLevel1__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicNavLevel1__ArgsType;
export const PlasmicNavLevel1__ArgProps = new Array<ArgPropType>("children");

export type PlasmicNavLevel1__OverridesType = {
  root?: p.Flex<"nav">;
  freeBox?: p.Flex<"div">;
  iconButton?: p.Flex<typeof IconButton>;
};

export interface DefaultNavLevel1Props {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicNavLevel1__RenderFunc(props: {
  variants: PlasmicNavLevel1__VariantsArgs;
  args: PlasmicNavLevel1__ArgsType;
  overrides: PlasmicNavLevel1__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <nav
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-labelledby={"" as const}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        plasmic_dls_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <IconButton
          data-plasmic-name={"iconButton"}
          data-plasmic-override={overrides.iconButton}
          className={classNames("__wab_instance", sty.iconButton)}
        />

        {p.renderPlasmicSlot({
          defaultContents: "Messages",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </div>
    </nav>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "iconButton"],
  freeBox: ["freeBox", "iconButton"],
  iconButton: ["iconButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "nav";
  freeBox: "div";
  iconButton: typeof IconButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavLevel1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavLevel1__VariantsArgs;
    args?: PlasmicNavLevel1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavLevel1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavLevel1__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavLevel1__ArgProps,
      internalVariantPropNames: PlasmicNavLevel1__VariantProps
    });

    return PlasmicNavLevel1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavLevel1";
  } else {
    func.displayName = `PlasmicNavLevel1.${nodeName}`;
  }
  return func;
}

export const PlasmicNavLevel1 = Object.assign(
  // Top-level PlasmicNavLevel1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    iconButton: makeNodeComponent("iconButton"),

    // Metadata about props expected for PlasmicNavLevel1
    internalVariantProps: PlasmicNavLevel1__VariantProps,
    internalArgProps: PlasmicNavLevel1__ArgProps
  }
);

export default PlasmicNavLevel1;
/* prettier-ignore-end */
