// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 72tUXrciMYQcBHG6D1vyXy
// Component: 51ipchq1cPeKS
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 5DE4ToOecQeHY/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_dls_css from "../dls/plasmic_dls.module.css"; // plasmic-import: wKYGFqyVBmDVb7fPCj2tLF/projectcss
import projectcss from "./plasmic_copy_of_text_messaging_app.module.css"; // plasmic-import: 72tUXrciMYQcBHG6D1vyXy/projectcss
import sty from "./PlasmicChatHeader.module.css"; // plasmic-import: 51ipchq1cPeKS/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: stDZdaEWpQOmVV/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: _YyChvp-V52F2m/icon

export type PlasmicChatHeader__VariantMembers = {};

export type PlasmicChatHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicChatHeader__VariantsArgs;
export const PlasmicChatHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicChatHeader__ArgsType = {};
type ArgPropType = keyof PlasmicChatHeader__ArgsType;
export const PlasmicChatHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicChatHeader__OverridesType = {
  chatHeader?: p.Flex<"nav">;
  button?: p.Flex<typeof Button>;
  h2?: p.Flex<"h2">;
};

export interface DefaultChatHeaderProps {
  className?: string;
}

function PlasmicChatHeader__RenderFunc(props: {
  variants: PlasmicChatHeader__VariantsArgs;
  args: PlasmicChatHeader__ArgsType;
  overrides: PlasmicChatHeader__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"nav"}
      data-plasmic-name={"chatHeader"}
      data-plasmic-override={overrides.chatHeader}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        plasmic_dls_css.plasmic_tokens,
        sty.chatHeader
      )}
      role={"" as const}
    >
      <Button
        data-plasmic-name={"button"}
        data-plasmic-override={overrides.button}
        className={classNames("__wab_instance", sty.button)}
      >
        {"back"}
      </Button>

      <h2
        data-plasmic-name={"h2"}
        data-plasmic-override={overrides.h2}
        className={classNames(
          projectcss.all,
          projectcss.h2,
          projectcss.__wab_text,
          sty.h2
        )}
      >
        {"Messages"}
      </h2>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  chatHeader: ["chatHeader", "button", "h2"],
  button: ["button"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  chatHeader: "nav";
  button: typeof Button;
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChatHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChatHeader__VariantsArgs;
    args?: PlasmicChatHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChatHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChatHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChatHeader__ArgProps,
      internalVariantPropNames: PlasmicChatHeader__VariantProps
    });

    return PlasmicChatHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "chatHeader") {
    func.displayName = "PlasmicChatHeader";
  } else {
    func.displayName = `PlasmicChatHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicChatHeader = Object.assign(
  // Top-level PlasmicChatHeader renders the root element
  makeNodeComponent("chatHeader"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicChatHeader
    internalVariantProps: PlasmicChatHeader__VariantProps,
    internalArgProps: PlasmicChatHeader__ArgProps
  }
);

export default PlasmicChatHeader;
/* prettier-ignore-end */
