// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicNavLevel1,
  DefaultNavLevel1Props
} from "./plasmic/copy_of_text_messaging_app/PlasmicNavLevel1";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface NavLevel1Props extends Omit<DefaultNavLevel1Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultNavLevel1Props altogether and have
// total control over the props for your component.
export interface NavLevel1Props extends DefaultNavLevel1Props {}

function NavLevel1_(props: NavLevel1Props, ref: HTMLElementRefOf<"nav">) {
  // Use PlasmicNavLevel1 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicNavLevel1 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all NavLevel1Props here, but feel free
  // to do whatever works for you.

  return <PlasmicNavLevel1 root={{ ref }} {...props} />;
}

const NavLevel1 = React.forwardRef(NavLevel1_);
export default NavLevel1;
